"""
عين AI — Discovery cache.

Stores trending topics generated by clustering NewsData.io headlines with GPT-4o-mini.
Refreshed every 4 hours (lazy: on first request after staleness).

The cache is a JSON file on disk so it survives single-process restarts and is shared
across worker threads. On read-only filesystems we fall back to a tempdir.
"""
import os
import json
import time
import tempfile
import threading
from pathlib import Path
from typing import Dict, Any, Optional

from newsdata_client import newsdata_client
from ain_ai import cluster_trending_topics


CACHE_TTL_SECONDS = 4 * 60 * 60  # 4 hours
DEFAULT_LANGUAGE = "ar"
DISCOVERY_BATCH_SIZE = 50  # how many headlines to feed the clusterer


# Resolve a writable cache directory.
def _cache_dir() -> Path:
    candidate = Path(__file__).resolve().parent / "data"
    try:
        candidate.mkdir(parents=True, exist_ok=True)
        # Smoke test write
        probe = candidate / ".write_test"
        probe.write_text("ok", encoding="utf-8")
        probe.unlink(missing_ok=True)
        return candidate
    except Exception:
        # Fallback to tempdir
        return Path(tempfile.gettempdir())


_CACHE_DIR = _cache_dir()
_lock = threading.Lock()
_inflight: Dict[str, threading.Event] = {}  # language -> in-flight refresh signal


def _cache_path(language: str) -> Path:
    safe_lang = "".join(c for c in (language or DEFAULT_LANGUAGE).lower() if c.isalpha()) or "ar"
    return _CACHE_DIR / f"ain_ai_discovery_{safe_lang}.json"


def _read_cache(language: str) -> Optional[dict]:
    path = _cache_path(language)
    try:
        if not path.exists():
            return None
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            return None
        return data
    except Exception as e:
        print(f"[ain_ai_cache] read error: {e}")
        return None


def _write_cache(language: str, payload: dict) -> None:
    path = _cache_path(language)
    tmp_path = path.with_suffix(".tmp")
    try:
        with tmp_path.open("w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False)
        tmp_path.replace(path)  # atomic on POSIX & Windows
    except Exception as e:
        print(f"[ain_ai_cache] write error: {e}")
        try:
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass


def _is_fresh(payload: Optional[dict]) -> bool:
    """A payload is 'fresh' only if recent AND it has actual topics.
    An empty-topics payload means the last build failed; we want to retry
    rather than serve nothing for 4 hours."""
    if not payload:
        return False
    ts = payload.get("generated_at_ts")
    if not isinstance(ts, (int, float)):
        return False
    if (time.time() - float(ts)) >= CACHE_TTL_SECONDS:
        return False
    topics = payload.get("topics") or []
    if not topics:
        return False
    return True


# ---------------------------------------------------------------------------
# Refresh pipeline
# ---------------------------------------------------------------------------

def _build_payload(language: str) -> dict:
    """Fetch latest headlines + cluster them. Returns the payload dict to persist."""
    fetch_result = newsdata_client.search_latest(
        language=language,
        size=DISCOVERY_BATCH_SIZE,
        remove_duplicate=True,
    )

    articles_raw = []
    fetch_error = None
    if fetch_result.get("success"):
        articles_raw = fetch_result.get("results") or []
    else:
        fetch_error = fetch_result.get("error") or "فشل جلب الأخبار."

    topics = []
    cluster_error = None
    if articles_raw:
        try:
            topics = cluster_trending_topics(articles_raw, language=language) or []
        except Exception as e:
            cluster_error = str(e)[:200]
            print(f"[ain_ai_cache] cluster error: {e}")

    return {
        "language": language,
        "generated_at_ts": time.time(),
        "generated_at_iso": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "topics": topics,
        "source_article_count": len(articles_raw),
        "fetch_error": fetch_error,
        "cluster_error": cluster_error,
    }


def refresh(language: str = DEFAULT_LANGUAGE) -> dict:
    """
    Force a refresh of the discovery cache for the given language.
    Returns the new payload.
    Concurrent callers for the same language wait for the in-flight refresh
    to finish instead of duplicating the API spend.
    """
    language = (language or DEFAULT_LANGUAGE).lower()

    # Coalesce concurrent refreshes
    with _lock:
        ev = _inflight.get(language)
        if ev is not None:
            # Another thread is already refreshing; wait for it
            wait_event = ev
            do_work = False
        else:
            wait_event = threading.Event()
            _inflight[language] = wait_event
            do_work = True

    if not do_work:
        # Wait up to 60s for the in-flight refresh; then read cache
        wait_event.wait(timeout=60)
        cached = _read_cache(language)
        return cached or {"language": language, "topics": [], "generated_at_ts": 0}

    try:
        payload = _build_payload(language)
        _write_cache(language, payload)
        return payload
    finally:
        with _lock:
            _inflight.pop(language, None)
        wait_event.set()


def get_discovery(language: str = DEFAULT_LANGUAGE, force: bool = False) -> dict:
    """
    Return the discovery payload for the given language.
    Refreshes lazily if the cache is stale or missing.
    """
    language = (language or DEFAULT_LANGUAGE).lower()
    cached = _read_cache(language)
    if not force and _is_fresh(cached):
        return cached
    return refresh(language)


def get_status(language: str = DEFAULT_LANGUAGE) -> dict:
    """Lightweight status check for admin UI."""
    language = (language or DEFAULT_LANGUAGE).lower()
    cached = _read_cache(language)
    if not cached:
        return {"language": language, "exists": False, "fresh": False, "topics_count": 0}
    return {
        "language": language,
        "exists": True,
        "fresh": _is_fresh(cached),
        "topics_count": len(cached.get("topics") or []),
        "generated_at_iso": cached.get("generated_at_iso"),
        "age_seconds": int(time.time() - float(cached.get("generated_at_ts") or 0)),
        "fetch_error": cached.get("fetch_error"),
        "cluster_error": cached.get("cluster_error"),
    }
